{{- if and .Values.server.persistence.enabled (not .Values.server.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "immich.mediaClaim" . }}
  labels:
    {{- include "immich.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.server.persistence.size }}
  {{- with .Values.server.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
