{{- if not .Values.pds.config.secrets.existingSecret }} 
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "bluesky-pds.fullname" . }}-secret"
  labels: 
    {{- include "bluesky-pds.labels" . | nindent 4 }}
data:
  jwtSecret: {{ randAlphaNum 16 | b64enc | quote }}
  plcRotationKey: {{ genPrivateKey "ecdsa" | trimPrefix "-----BEGIN EC PRIVATE KEY-----" | trimSuffix "-----END EC PRIVATE KEY-----" | printf "%x" | substr 0 64 | quote }}
  adminPassword: {{ .Values.pds.config.secrets.adminPassword | b64enc | quote }}
  emailSmtpUrl: {{ .Values.pds.config.secrets.emailSmtpUrl | b64enc | quote }}
type: Opaque
{{- end }}
