{{- if not .Values.pds.config.secrets.existingSecret }} 
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "bluesky-pds.fullname" . }}-secret"
  labels: 
    {{- include "bluesky-pds.labels" . | nindent 4 }}
data:
  jwtSecret: {{ (or (.Values.pds.config.secrets.jwtSecret) (randAlphaNum 16)) | b64enc | quote }}
  plcRotationKey: {{ (or (.Values.pds.config.secrets.plcRotationKey) (genPrivateKey "ecdsa" | trim | trimPrefix "-----BEGIN EC PRIVATE KEY-----" | trimSuffix "-----END EC PRIVATE KEY-----" | printf "%x" | substr 0 64)) | b64enc | quote }}
  adminPassword: {{ (or (.Values.pds.config.secrets.adminPassword) (randAlphaNum 16)) | b64enc | quote }}
  emailSmtpUrl: {{ .Values.pds.config.secrets.emailSmtpUrl | b64enc | quote }}
type: Opaque
{{- end }}
