# https://docs.immich.app/install/environment-variables
env:
  IMMICH_TRUSTED_PROXIES: []
  DB_VECTOR_EXTENSION: vectorchord
  # DB_URL:
  #   valueFrom:
  #     secretKeyRef:
  #       name: postgres-secret
  #       key: jdbc-uri
  # REDIS_HOSTNAME: ""
  # REDIS_PASSWORD:
  #   valueFrom:
  #     secretKeyRef:
  #       name: redis-secret
  #       key: password

server:
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent
    tag: ""
  # https://docs.immich.app/administration/jobs-workers
  frontend: # configuration for the api-worker enabled server instances
    replicaCount: 1
    service:
      type: ClusterIP
      port: 2283
  backend: # configuration for the microservices-worker enabled server instances
    replicaCount: 1
    service:
      type: ClusterIP
      port: 2283
  # storage for the immich media directory
  persistence:
    size: 10Gi
    storageClass: ""
    accessMode: ReadWriteMany

machineLearning:
  replicaCount: 1
  image:
    repository: ghcr.io/immich-app/immich-machine-learning
    pullPolicy: IfNotPresent
    tag: ""
  service:
    type: ClusterIP
    port: 3003
  model:
    persistence:
      type: emptyDir
